name: Build JAR on Release

on:
  release:
    types:
      - created

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "21"
      - run: mvn clean package
      - run: |
          gh release upload "${{ github.event.release.tag_name }}" target/*.jar --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
